config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'

  get '/about', to: 'about#index'

  get '/register', to: 'registrations#new'
  post '/register', to: 'registrations#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  get '/change-password', to: 'passwords#edit'
  patch '/change-password', to: 'passwords#update'

  get '/forgot-password', to: 'password_resets#new'
  post '/forgot-password', to: 'password_resets#create'

  get '/reset-password', to: 'password_resets#edit'
  patch '/reset-password', to: 'password_resets#update'

  get '/auth/twitter/callback', to: 'omniauth_callback#twitter'

  resources :twitter_accounts
  resources :tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: {
    minimum: 1,
    maximum: 280
  }
  validates :publish_at, presence: true

  after_initialize do
    self.publish_at ||= 1.day.from_now
  end

  after_save_commit do
    if publish_at_previously_changed?
      TweetJob.set(wait_until: publish_at).perform_later(self)
    end
  end

  def published?
    tweet_id?
  end

  def publish_to_twitter!
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)
  end
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  belongs_to :user

  has_many :tweets, dependent: :destroy

  validates :username, uniqueness: true

  def client
    Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.credentials.dig(:twitter, :api_key)
      config.consumer_secret     = Rails.application.credentials.dig(:twitter, :api_secret)
      config.access_token        = token
      config.access_token_secret = secret
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :twitter_accounts
  has_many :tweets

  has_secure_password

  validates :email, presence: true, format: {
    with: URI::MailTo::EMAIL_REGEXP,
    message: 'must be a valid email address'
  }
  validates :password, presence: true
  validates :password_confirmation, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def require_user_logged_in!
    if Current.user.nil?
      redirect_to login_path, alert: 'You must be signed in to do that.'
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  before_action :require_user_logged_in!

  def edit
  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: 'Password updated successfully.'
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!

  def edit
  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: 'Password updated successfully.'
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def new
    if Current.user.nil?
      @user = User.new
    else
      redirect_to root_path
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, notice: 'Registered successfully.'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in successfully.'
    else
      flash[:alert] = 'Invalid email or password.'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out successfully.'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in successfully.'
    else
      flash[:alert] = 'Invalid email or passwords.'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out successfully.'
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  def index
    @tweets = Current.user.tweets
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Current.user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to tweets_path, notice: 'Tweet was scheduled successfully.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice: 'Tweet was updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice: 'Tweet was unscheduled successfully.'
  end

  private

  def tweet_params
    params.require(:tweet).permit(:twitter_account_id, :body, :publish_at)
  end

  def set_tweet
    @tweet = Current.user.tweets.find(params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_active?(path)
    "active" if current_page? path
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/twitter_accounts_helper.rb
module TwitterAccountsHelper
end

app/views/session/new.html.erb
<h2 class="text-center">Login</h2>
<div class="form-container my-4 mx-auto">
  <%= form_with url: login_path, method: :post do |form| %>
    <div class="mb-3">
      <%= form.label :email %>
      <%= form.email_field :email, class: 'mt-2 form-control' %>
    </div>
    <div class="mb-3">
      <%= form.label :password %>
      <%= form.password_field :password, class: 'mt-2 form-control' %>
    </div>
    <div class="d-grid gap-2 d-md-flex">
      <%= link_to 'Go Home', root_path, class: 'btn btn-secondary col-md-6' %>
      <%= form.submit 'Login', class: 'btn btn-primary col-md-6', type: 'submit' %>
    </div>
    <div class="mt-4 text-center">
      <%= link_to 'Forgot Password?', forgot_password_path %>
    </div>
  <% end %>
</div>

app/views/tweets/_form.html.erb
<%= form_with model: tweet do |form| %>
  <%= render 'shared/form_errors', form: form %>
  <div class="mb-3">
    <%= form.label :twitter_account_id %>
    <div class="mt-2 d-flex align-items-between justify-content-center">
      <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, {
        class: 'form-control'
      } %>
      <%= link_to 'Add', '/auth/twitter', method: :post, class: 'ms-4 btn btn-primary' %>
    </div>
  </div>
  <div class="mb-3">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'mt-2 form-control', rows: 5 %>
  </div>
  <div class="mb-3">
    <%= form.label :publish_at %>
    <div class="mt-2 form-control">
      <%= form.datetime_select :publish_at %>
    </div>
  </div>
  <div class="mt-3">
    <%= form.submit 'Schedule', class: 'btn btn-primary' %>
    <% if form.object.persisted? %>
      <%= link_to 'Delete', form.object, method: :delete, data: {
        confirm: 'Are you sure?'
      }, class: 'btn btn-danger ms-2' %>
    <% end %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="card card-body mb-3 d-flex flex-row justify-content-between align-items-center">
  <%= tweet.body %>
  <div class="ms-4">
    <% if tweet.published? %>
      <%= link_to 'View', "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}", target: :_blank %>
    <% else %>
      <span>Scheduled for <%= l tweet.publish_at, format: :long %></span>
      <%= link_to 'Edit', edit_tweet_path(tweet) %>
    <% end %>
    <%= image_tag tweet.twitter_account.image, class: 'rounded-circle mx-2' %>
    <%= link_to "@#{tweet.twitter_account.username}", "https://twitter.com/#{tweet.twitter_account.username}", target: :_blank %>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="my-4">
  <h2 class="text-center">Edit Tweet</h2>
</div>

<%= render 'form', tweet: @tweet %>

app/views/tweets/index.html.erb
<div class="d-flex align-items-center justify-content-between">
  <h2 class="text-center">Tweets</h2>
  <% if Current.user.twitter_accounts.any? %>
    <div class="my-4">
      <%= link_to 'Schedule Tweet', new_tweet_path, class: 'btn btn-lg btn-primary' %>
    </div>
  <% elsif Current.user.twitter_accounts.none? %>
    <div class="my-4">
      <%= button_to 'Connect Twitter', '/auth/twitter', method: :post, class: 'btn btn-lg btn-primary' %>
    </div>
  <% end %>
</div>

<%= render @tweets.order(created_at: :desc) %>

app/views/tweets/new.html.erb
<div class="my-4">
  <h2 class="text-center">Schedule a Tweet</h2>
</div>

<%= render 'form', tweet: @tweet %>