config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'

  get '/about', to: 'about#index'

  get '/register', to: 'registrations#new'
  post '/register', to: 'registrations#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  get '/change-password', to: 'passwords#edit'
  patch '/change-password', to: 'passwords#update'

  get '/forgot-password', to: 'password_resets#new'
  post '/forgot-password', to: 'password_resets#create'

  get '/reset-password', to: 'password_resets#edit'
  patch '/reset-password', to: 'password_resets#update'

  get '/auth/twitter/callback', to: 'omniauth_callback#twitter'

  resources :twitter_accounts
  resources :tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: {
    minimum: 1,
    maximum: 280
  }
  validates :publish_at, presence: true

  after_initialize do
    self.publish_at ||= 1.day.from_now
  end

  after_save_commit do
    if publish_at_previously_changed?
      TweetJob.set(wait_until: publish_at).perform_later(self)
    end
  end

  def published?
    tweet_id?
  end

  def publish_to_twitter!
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)
  end
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  belongs_to :user

  has_many :tweets, dependent: :destroy

  validates :username, uniqueness: true

  def client
    Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.credentials.dig(:twitter, :api_key)
      config.consumer_secret     = Rails.application.credentials.dig(:twitter, :api_secret)
      config.access_token        = token
      config.access_token_secret = secret
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :twitter_accounts
  has_many :tweets

  has_secure_password

  validates :email, presence: true, format: {
    with: URI::MailTo::EMAIL_REGEXP,
    message: 'must be a valid email address'
  }
  validates :password, presence: true
  validates :password_confirmation, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  before_action :require_user_logged_in!

  def edit
  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: 'Password updated successfully.'
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in successfully.'
    else
      flash[:alert] = 'Invalid email or password.'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out successfully.'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in successfully.'
    else
      flash[:alert] = 'Invalid email or passwords.'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out successfully.'
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  def index
    @tweets = Current.user.tweets
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Current.user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to tweets_path, notice: 'Tweet was scheduled successfully.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice: 'Tweet was updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice: 'Tweet was unscheduled successfully.'
  end

  private

  def tweet_params
    params.require(:tweet).permit(:twitter_account_id, :body, :publish_at)
  end

  def set_tweet
    @tweet = Current.user.tweets.find(params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_active?(path)
    "active" if current_page? path
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/twitter_accounts_helper.rb
module TwitterAccountsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BufferClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <div class="container m-4 mx-auto">
      <%= render 'shared/messages' %>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <script type="text/javascript">
        window.setTimeout(() => {
            document.querySelectorAll(".alert").forEach((e, i) => {
                setTimeout(() => e.remove(), i * 2000);
            });
        }, 4000);
    </script>
  </body>
</html>

app/views/shared/_form_errors.html.erb
<% if form.object.errors.any? %>
  <% form.object.errors.full_messages.each do |message| %>
    <div class="alert alert-danger alert-dismissible fade show m-4 mx-0" role="alert">
      <i class="fa fa-exclamation-triangle"></i>
      <%= content_tag :span, message, class: 'mx-2' %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>

app/views/shared/_messages.html.erb
<% if flash.any? %>
    <% flash.each do |name, message| %>
      <div class="alert alert-<%= name.to_s == 'notice' ? 'info' : 'danger' %> alert-dismissible fade show my-4" role="alert">
        <i class="fa fa-<%= name.to_s == 'notice' ? 'exclamation-circle' : 'exclamation-triangle' %>"></i>
        <%= content_tag :span, message, :id => "flash_#{name}", class: 'mx-2' %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Buffer', root_path, class: 'navbar-brand mx-4' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About', about_path, class: "nav-link #{link_active? about_path}" %>
        </li>
        <% if Current.user %>
          <li class="nav-item">
            <%= link_to 'Tweets', tweets_path, class: "nav-link #{link_active? tweets_path}" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Accounts', twitter_accounts_path, class: "nav-link #{link_active? twitter_accounts_path}" %>
          </li>
        <% end %>
      </ul>
      <div class="d-flex align-items-center">
        <% if Current.user %>
          <div class="nav-item">
            <%= link_to Current.user.email, change_password_path, class: 'nav-link text-light' %>
          </div>
          <div class="mx-4">
            <%= button_to 'Logout', logout_path, class: 'btn btn-light', method: :delete %>
          </div>
        <% else %>
          <div class="mr-2">
            <%= link_to 'Register', register_path, class: 'btn btn-primary' %>
          </div>
          <div class="mx-4">
            <%= link_to 'Login', login_path, class: 'btn btn-light' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>